2025-08-06 07:40:59.980305 - User: Anonymous - Path: /admin/
2025-08-06 07:40:59.998008 - User: Anonymous - Path: /admin/login/
2025-08-06 07:41:09.450474 - User: Anonymous - Path: /admin/
2025-08-06 07:41:09.458492 - User: Anonymous - Path: /admin/login/
2025-08-06 07:41:11.453351 - User: Anonymous - Path: /api/conversations/
Forbidden: /api/conversations/
2025-08-06 07:53:46.177144 - User: Anonymous - Path: /api/conversations/
Forbidden: /api/conversations/
2025-08-06 07:54:03.252680 - User: Anonymous - Path: /admin/
2025-08-06 07:54:03.257646 - User: Anonymous - Path: /admin/login/
2025-08-06 07:54:10.092707 - User: Anonymous - Path: /admin/login/
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: chats_user.user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/forms/forms.py", line 206, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/forms/forms.py", line 201, in errors
    self.full_clean()
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/forms/forms.py", line 338, in full_clean
    self._clean_form()
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/forms/forms.py", line 354, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/views/decorators/debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/contrib/auth/forms.py", line 366, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/views/decorators/debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/contrib/auth/__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/contrib/auth/backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/contrib/auth/base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sherif/alx-backend-python/Django-Middleware-0x03/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: chats_user.user_id
2025-08-06 08:34:53.598530 - User: Anonymous - Path: /admin/
2025-08-06 08:34:53.615915 - User: Anonymous - Path: /admin/login/
2025-08-06 08:35:02.330399 - User: Anonymous - Path: /admin/login/
2025-08-06 08:35:18.100109 - User: Anonymous - Path: /admin/login/
2025-08-06 08:35:18.981817 - User: sherif425@gmail.com - Path: /admin/
2025-08-06 08:35:25.210872 - User: sherif425@gmail.com - Path: /admin/chats/message/
2025-08-06 08:35:25.317253 - User: sherif425@gmail.com - Path: /admin/jsi18n/
2025-08-06 08:35:30.933034 - User: sherif425@gmail.com - Path: /admin/chats/conversation/
2025-08-06 08:35:31.018538 - User: sherif425@gmail.com - Path: /admin/jsi18n/
2025-08-06 08:35:34.028426 - User: sherif425@gmail.com - Path: /admin/auth/group/
2025-08-06 08:35:34.103965 - User: sherif425@gmail.com - Path: /admin/jsi18n/
2025-08-06 08:35:36.341241 - User: sherif425@gmail.com - Path: /admin/chats/message/
2025-08-06 08:35:36.423642 - User: sherif425@gmail.com - Path: /admin/jsi18n/
2025-08-06 08:35:37.742919 - User: sherif425@gmail.com - Path: /admin/chats/conversation/
2025-08-06 08:35:37.820031 - User: sherif425@gmail.com - Path: /admin/jsi18n/
2025-08-06 08:53:26.412617 - User: sherif425@gmail.com - Path: /admin/chats/conversation/
Forbidden: /admin/chats/conversation/
2025-08-06 08:53:31.493886 - User: sherif425@gmail.com - Path: /admin/
Forbidden: /admin/
2025-08-06 08:53:31.847009 - User: sherif425@gmail.com - Path: /admin/
Forbidden: /admin/
/home/sherif/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
/home/sherif/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
2025-08-06 08:59:26.935270 - User: sherif425@gmail.com - Path: /admin/
Forbidden: /admin/
2025-08-06 08:59:56.918953 - User: Anonymous - Path: /chats/send/
Forbidden: /chats/send/
